title = "Zhou Yi"
languageCode = "zh-CN"
baseurl = "http://shirleychou.github.io/my-blog/"
Copyright = "Copyright (c) 2016. All rights reserved."
theme = "casper"
paginate = 5
DisqusShortname = "shirley"


[params]
description = "Recording... Action!"
cover = "images/cover_polenord.jpg"
author = "Zhou Yi"
authorlocation = "Beijing, China"
# authorwebsite = ""
bio= "Back-end software engineer, Machine Learning and Data Mining enthusiast."
logo = "images/logo.png"
googleAnalyticsUserID = "UA-79101-12"
githubName = "shirleyChou"
# twitterName = "vjeantet"
# set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
hideHUGOSupport = false
Categories = ["读书笔记", "技术文章", "思考感悟"]

[permalinks]
post = "/:year/:month/:day/:slug/"

[[menu.main]]
name = "Blog"
weight = -120
identifier = "blog"
url = "/"

[[menu.main]]
name = "Github repos"
weight = 100
pre = "<h3>Follow me</h3>"
url = "https://github.com/shirleyChou"

